export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const GET_WALLET_PROFILE_DATA = 'GET_WALLET_PROFILE_DATA';
export const GET_PROPERTY_LIST = 'GET_PROPERTY_LIST';
export const MY_TRANSACTIONS_LIST = 'MY_TRANSACTIONS_LIST';
export const GET_HOME_PAGE_DATA = 'GET_HOME_PAGE_DATA';
