export const font = {
  bold: 'SourceSans3-Bold',
  light: 'SourceSans3-Light',
  medium: 'SourceSans3-Medium',
  xbold: 'SourceSans3-ExtraBold',
  regular: 'SourceSans3-Regular',
  blackBold: 'SourceSans3-Black',
  xlight: 'SourceSans3-ExtraLight',
  semiBold: 'SourceSans3-SemiBold',
  qRegular: 'Quicksand-Regular',
  qMedium: 'Quicksand-Medium',
  qBold: 'Quicksand-Bold',
  qSemiBold: 'Quicksand-SemiBold',
  mRegular: 'Mukta-Regular',
  mMedium: 'Mukta-Medium',
  mBold: 'Mukta-Bold',
  mrBold: 'Manrope-Bold',
  mrRegular: 'Manrope-Regular',
  mrMedium: 'Manrope-Medium',
  mrSemiBold: 'Manrope-SemiBold',
  pRegular: 'Poppins-Regular',
  pMedium: 'Poppins-Medium',
  pBold: 'Poppins-Bold',
  pSemiBold: 'Poppins-SemiBold',
};
