export const SCREEN = {
  WELCOME: 'Welcome',
  LOGIN: 'Login',
  OTP: 'Otp',
  SIGNUP: 'SignUp',
  HOME: 'Home',
  BOTTOMTABS: 'BottomTabs',
  MARKET: 'Market',
  PORTFOLIO: 'Portfolio',
  TRANSACTION: 'Transaction',
  PROFILE: 'Profile',
  NOTIFICATION: 'Notification',
  PAYMENT: 'Payment',
  PROPERTYDETAILS: 'PropertyDetails',
  INVESTSCREEN: 'InvestScreen',
  PROPERTYLIST: 'PropertyList',
  BROKERSTAB: 'BrokersTab',
  DASHBOARD: 'Dashboard',
  PROPERTIES: 'Properties',
  CUSTOMERS: 'Customers',
  ORDERS: 'Orders',
  PROPERTYDETAILSBROKER: 'PropertyDetailsBroker',
  CUSTOMERDETAILS: 'CustomerDetails',
  ADDCUSTOMER: 'AddCustomer',
  ORDERDETAILS: 'OrderDetails',
  ADDORDERS: 'AddOrders',
};
